---
title: "E-Business Loan Status Prediction"
output: 
  html_document:
    keep_md: true
---

# Load libraries

```{r}
library(tidyverse)
library(caret)
library(randomForest)
library(e1071)
library(pROC)
library(rpart)
library(ggplot2)
```

# Load & Transform the data

```{r}
# Load the data
rawData <- read.csv("loan_data.csv")

# Transform the data
rawData <- rawData %>%
  select(-Loan_ID) %>%
  mutate(Married = Married == "Yes",
         Education = Education == "Graduate",
         Self_Employed = Self_Employed == "Yes",
         Gender = as.factor(Gender),
         Dependents = as.factor(Dependents),
         Property_Area = as.factor(Property_Area),
         Loan_Status = factor(ifelse(Loan_Status == "Y", "Yes", "No")))
```

# Feature Engineering

```{r}
rawData <- rawData %>%
  mutate(Total_Income = ApplicantIncome + CoapplicantIncome,
         Income_to_Loan = Total_Income / LoanAmount)

# Drop all missing values just for testing TODO
rawData <- drop_na(rawData)

# Check for null values and handle them (if any)
null_counts <- colSums(is.na(rawData))
print(null_counts)
```

```{r}
# Save the data as a csv #TODO
write.csv(rawData, "C:/Users/timst/Documents/GitHub/E-Business-Loan-Status-Prediction/rawData.csv")
```

# Initial Data sighting

```{r}
# Plot 1: Distribution of Loan Status with customized colors
ggplot(rawData, aes(x = Loan_Status, fill = Loan_Status)) +
  geom_bar() +
  scale_fill_manual(values = c("TRUE" = "#90EE90", "FALSE" = "#FFB6C1")) +
  ggtitle("Distribution of Loan Status") +
  theme_minimal()

# Plot 2: Distribution of Gender with customized RGB colors
ggplot(rawData, aes(x = Gender, fill = Gender)) +
  geom_bar() +
  scale_fill_manual(values = c("Male" = "#89CFF0", "Female" = "#FFB6C1")) +
  ggtitle("Distribution of Gender") +
  theme_minimal()

# Plot 3: Average Loan Amount by Property Area
avg_loan_amount <- rawData %>%
  group_by(Property_Area) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Property_Area, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  ggtitle("Average Loan Amount by Property Area") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 4: Distribution of Loan Status by Education
ggplot(rawData, aes(x = Loan_Status, fill = Education)) +
  geom_bar(position = "dodge") +
  ggtitle("Distribution of Loan Status by Education") +
  theme_minimal()

# Plot 5: Distribution of Loan Status by Self Employed status
ggplot(rawData, aes(x = Loan_Status, fill = Self_Employed)) +
  geom_bar(position = "dodge") +
  ggtitle("Distribution of Loan Status by Self Employed Status") +
  theme_minimal()
```


# EDA
```{r}
#Average Loan Amounts Requested and Granted

# Plot 1: Average Loan Amount requested by Gender
# Calculate the average loan amount by gender and remove missing values
avg_loan_amount_gender <- rawData %>%
  filter(!is.na(Gender) & Gender != "") %>%
  group_by(Gender) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Create the bar plot
ggplot(avg_loan_amount_gender, aes(x = Gender, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Gender") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 2: Average Loan Amount  granted granted by Gender
# Calculate the average loan amount by gender and remove missing values
avg_loan_amount_gender <- rawData %>%
  filter(Loan_Status == "TRUE" & !is.na(Gender) & Gender != "") %>%
  group_by(Gender) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Create the bar plot
ggplot(avg_loan_amount_gender, aes(x = Gender, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount granted by Gender") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 3: Average Loan Amount requested by Property Area
avg_loan_amount <- rawData %>%
  group_by(Property_Area) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Property_Area, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Property Area") +
  ylab("Average Loan Amount") +
  theme_minimal()


# Plot 4: Average Loan Amount granted by Property Area
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Property_Area) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Property_Area, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Property Area") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 5: Average Loan Amount requested by Marriage Status
avg_loan_amount <- rawData %>%
  group_by(Married) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Married, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Marriage Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 6: Average Loan Amount granted by Marriage Status
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Married) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Married, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Marriage Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 7: Average Loan Amount requested by Education Status
avg_loan_amount <- rawData %>%
  group_by(Education) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Education, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Education Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 8: Average Loan Amount granted by Education Status
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Education) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Education, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Education Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 9: Average Loan Amount requested by Self_Employed Status
avg_loan_amount <- rawData %>%
  group_by(Self_Employed) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Self_Employed, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Self_Employed Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 10: Average Loan Amount granted by Self_Employed Status
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Self_Employed) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Self_Employed, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Self_Employed Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 11: Average Loan Amount requested by Number of Dependents
avg_loan_amount <- rawData %>%
  group_by(Dependents) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Dependents, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Number of Dependents") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 12: Average Loan Amount granted by Number of Dependents
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Dependents) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Dependents, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Number of Dependents") +
  ylab("Average Loan Amount") +
  theme_minimal()


# Plot 13: Average loan amount requested by Applicant Income
avg_loan_requested <- rawData %>%
  group_by(ApplicantIncome) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount requested with a trend line
ggplot(avg_loan_requested, aes(x = ApplicantIncome, y = LoanAmount)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  ggtitle("Average Loan Amount Requested by Applicant Income") +
  xlab("Applicant Income") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 14: Average loan amount granted by Applicant Income (Loan_Status == TRUE)
avg_loan_granted <- rawData %>%
  filter(Loan_Status == TRUE) %>%
  group_by(ApplicantIncome) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount granted with a trend line
ggplot(avg_loan_granted, aes(x = ApplicantIncome, y = LoanAmount)) +
  geom_line(color = "green") +
  geom_point(color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  ggtitle("Average Loan Amount Granted by Applicant Income") +
  xlab("Applicant Income") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 15: Average loan amount requested by Coapplicant Income
avg_loan_requested <- rawData %>%
  group_by(CoapplicantIncome) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount requested with a trend line
ggplot(avg_loan_requested, aes(x = CoapplicantIncome, y = LoanAmount)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  ggtitle("Average Loan Amount Requested by Coapplicant Income") +
  xlab("Coapplicant Income") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 16: Average loan amount granted by Coapplicant Income (Loan_Status == TRUE)
avg_loan_granted <- rawData %>%
  filter(Loan_Status == TRUE) %>%
  group_by(CoapplicantIncome) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount granted with a trend line
ggplot(avg_loan_granted, aes(x = CoapplicantIncome, y = LoanAmount)) +
  geom_line(color = "green") +
  geom_point(color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  ggtitle("Average Loan Amount Granted by Coapplicant Income") +
  xlab("Coapplicant Income") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 17: Average loan amount requested by Total_Income
avg_loan_requested <- rawData %>%
  group_by(Total_Income) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount requested with a trend line
ggplot(avg_loan_requested, aes(x = Total_Income, y = LoanAmount)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  ggtitle("Average Loan Amount Requested by Total_Income") +
  xlab("TotalIncome") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 18: Average loan amount granted by Total_Income (Loan_Status == TRUE)
avg_loan_granted <- rawData %>%
  filter(Loan_Status == TRUE) %>%
  group_by(Total_Income) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount granted with a trend line
ggplot(avg_loan_granted, aes(x = Total_Income, y = LoanAmount)) +
  geom_line(color = "green") +
  geom_point(color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  ggtitle("Average Loan Amount Granted by Toal_Income") +
  xlab("Total_Income") +
  ylab("Average Loan Amount") +
  theme_minimal()


# Plot 19: Average loan amount requested by Income_to_Loan
avg_loan_requested <- rawData %>%
  group_by(Income_to_Loan) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount requested with a trend line
ggplot(avg_loan_requested, aes(x = Income_to_Loan, y = LoanAmount)) +
  geom_line() +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  ggtitle("Average Loan Amount Requested by Total_Income") +
  xlab("Income_to_Loan") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 20: Average loan amount granted by Income_to_Loan (Loan_Status == TRUE)
avg_loan_granted <- rawData %>%
  filter(Loan_Status == TRUE) %>%
  group_by(Income_to_Loan) %>%
  summarize(LoanAmount = mean(LoanAmount, na.rm = TRUE))

# Plotting average loan amount granted with a trend line
ggplot(avg_loan_granted, aes(x = Income_to_Loan, y = LoanAmount)) +
  geom_line(color = "green") +
  geom_point(color = "green") +
  geom_smooth(method = "lm", se = FALSE, color = "red") +
  ggtitle("Average Loan Amount Granted by Income_to_Loan") +
  xlab("Income_to_Loan") +
  ylab("Average Loan Amount") +
  theme_minimal()

  
# Plot 21: Average Loan Amount requested by Credit_History
avg_loan_amount <- rawData %>%
  group_by(Credit_History) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Credit_History, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Credit_History") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 22: Average Loan Amount granted by Credit_History
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Credit_History) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Credit_History, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Credit_History") +
  ylab("Average Loan Amount") +
  theme_minimal()


# Plot 23: Average Loan Amount requested by Loan_Amount_Term
avg_loan_amount <- rawData %>%
  group_by(Loan_Amount_Term) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Loan_Amount_Term, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Loan_Amount_Term") +
  ylab("Average Loan Amount") +
  theme_minimal()

# Plot 24: Average Loan Amount granted by Loan_Amount_Term
avg_loan_amount <- rawData %>%
  filter(Loan_Status == "TRUE") %>%
  group_by(Loan_Amount_Term) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Loan_Amount_Term, y = LoanAmount)) +
  geom_bar(stat = "identity", fill = "darkgreen") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) + #Add labels above bars
  ggtitle("Average Loan Amount granted by Loan_Amount_Term") +
  ylab("Average Loan Amount") +
  theme_minimal()


# Plot 25: Average Loan Amount requested by Loan_Status
avg_loan_amount <- rawData %>%
  group_by(Loan_Status) %>%
  summarize(LoanAmount = mean(LoanAmount))

ggplot(avg_loan_amount, aes(x = Loan_Status, y = LoanAmount)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = round(LoanAmount, 2)), vjust = -0.5) +  # Add labels above bars
  ggtitle("Average Loan Amount requested by Loan_Status") +
  ylab("Average Loan Amount") +
  theme_minimal()

```

# Model Training

```{r}
# Split Data into Training and Testing Sets
set.seed(123)
trainIndex <- createDataPartition(rawData$Loan_Status, p = .8, 
                                  list = FALSE, 
                                  times = 1)
X_train <- rawData[trainIndex,]
X_test <- rawData[-trainIndex,]
```

```{r}
# Ensure Loan_Status is a factor
X_train$Loan_Status <- as.factor(X_train$Loan_Status)
X_test$Loan_Status <- as.factor(X_test$Loan_Status)
```

```{r}
# Preprocessing
preprocess <- preProcess(X_train, method = c("center", "scale"))
X_train <- predict(preprocess, X_train)
X_test <- predict(preprocess, X_test)
```

### Train and Evaluate the Random Forest Model

```{r}
plot_roc_curve <- function(roc_obj, model_name) {
  ggroc(roc_obj, legacy.axes = TRUE) +
    geom_abline(linetype = "dashed", color = "gray") +
    ggtitle(paste("ROC Curve for", model_name, "Model")) +
    theme_minimal() +
    xlab("False Positive Rate") +
    ylab("True Positive Rate")
}
```

```{r}
# Define an expanded grid for Random Forest
rf_grid <- expand.grid(mtry = c(2, 4, 6, 8))    # Number of variables to try at each split      

# Define control for Random Forest with cross-validation
rf_control <- trainControl(method = "cv", number = 10)

# Train the Random Forest model with expanded grid
rf_model <- train(
  Loan_Status ~ ., 
  data = X_train, 
  method = "rf", 
  trControl = rf_control, 
  tuneGrid = rf_grid
)

# Predict on the test set
rf_predictions <- predict(rf_model, X_test)
conf_matrix <- confusionMatrix(rf_predictions, X_test$Loan_Status)

print("Confusion Matrix:")
print(conf_matrix)

# Extract metrics from confusion matrix
recall <- conf_matrix$byClass['Recall']
precision <- conf_matrix$byClass['Precision']
f1 <- 2 * (precision * recall) / (precision + recall)

# Get probabilities for ROC curve
rf_probs <- predict(rf_model, X_test, type = "prob")[, 2]

# Calculate ROC curve
rf_roc <- roc(X_test$Loan_Status, rf_probs)

# Plot ROC curve
print(plot_roc_curve(rf_roc, "Random Forest"))

# Calculate and display accuracy, AUC, recall, precision, and F1 score
rf_metrics <- data.frame(
  Accuracy = max(rf_model$results$Accuracy), 
  AUC = auc(rf_roc),
  Recall = recall,
  Precision = precision,
  F1_Score = f1
)
print(rf_metrics)

```

### Train and Evaluate the KNN Model

```{r}
# Define control for KNN with cross-validation
knn_control <- trainControl(method = "cv", number = 10)

# Train the KNN model with cross-validation
knn_model <- train(Loan_Status ~ ., data = X_train, method = "knn", tuneLength = 5, trControl = knn_control)

# Predict on the test set
knn_predictions <- predict(knn_model, X_test)
knn_conf_matrix <- confusionMatrix(knn_predictions, X_test$Loan_Status)

# Extract recall from confusion matrix
knn_recall <- knn_conf_matrix$byClass['Recall']

# Get probabilities for ROC curve
knn_probs <- predict(knn_model, X_test, type = "prob")[, 2]

# Calculate ROC curve
knn_roc <- roc(X_test$Loan_Status, knn_probs)

# Plot ROC curve
print(plot_roc_curve(knn_roc, "KNN"))

# Calculate and display accuracy, AUC, and recall
knn_metrics <- data.frame(
  Accuracy = max(knn_model$results$Accuracy), 
  AUC = auc(knn_roc),
  Recall = knn_recall
)
print(knn_metrics)


```

### Train and Evaluate the Decision Tree Model

```{r}
library(caret)
library(pROC)

# Define control for Decision Tree with cross-validation
dt_control <- trainControl(method = "cv", number = 10)

# Train the Decision Tree model with cross-validation
dt_model <- train(Loan_Status ~ ., data = X_train, method = "rpart", trControl = dt_control)

# Predict on the test set
dt_predictions <- predict(dt_model, X_test)
dt_conf_matrix <- confusionMatrix(dt_predictions, X_test$Loan_Status)

# Extract recall from confusion matrix
dt_recall <- dt_conf_matrix$byClass['Recall']

# Get probabilities for ROC curve
dt_probs <- predict(dt_model, X_test, type = "prob")[, 2]

# Calculate ROC curve
dt_roc <- roc(X_test$Loan_Status, dt_probs)

# Plot ROC curve
print(plot_roc_curve(dt_roc, "Decision Tree"))

# Calculate and display accuracy, AUC, and recall
dt_metrics <- data.frame(
  Accuracy = max(dt_model$results$Accuracy), 
  AUC = auc(dt_roc),
  Recall = dt_recall
)
print(dt_metrics)

```

# Compare Models

```{r}
model_comparison <- data.frame(
  Model = c("Random Forest", "KNN", "Decision Tree"),
  Accuracy = c(rf_metrics$Accuracy, knn_metrics$Accuracy, dt_metrics$Accuracy),
  AUC = c(rf_metrics$AUC, knn_metrics$AUC, dt_metrics$AUC),
  Recall = c(rf_metrics$Recall, knn_metrics$Recall, dt_metrics$Recall),
  
  
)

print(model_comparison)

```

# Identify the best model

```{r}
best_model_name <- model_comparison[which.max(model_comparison$AUC), "Model"]
print(paste("Best model based on AUC is:", best_model_name))

if (best_model_name == "Random Forest") {
  best_model <- rf_model$finalModel
  varImpPlot(best_model)
} else if (best_model_name == "Decision Tree") {
  best_model <- dt_model$finalModel
  rpart.plot(best_model)
}
```


# Best Model With CostMatrix and Recall Training
```{r}
library(caret)
library(randomForest)
library(pROC)

# Define control for Random Forest with cross-validation
rf_control <- trainControl(method = "cv", number = 10, classProbs = TRUE)

# Assign higher weight to the "No" class to penalize false positives more heavily
class_weights <- c("No" = 1, "Yes" = 100000)

# Define a custom training function for Random Forest to incorporate class weights
train_rf_with_weights <- function(train_data, train_labels, mtry) {
  randomForest(
    x = train_data,
    y = train_labels,
    mtry = mtry,
    classwt = class_weights
  )
}

# Create a custom train function for caret to use
rf_custom <- list(
  type = "Classification",
  library = "randomForest",
  loop = NULL,
  parameters = data.frame(parameter = "mtry", class = "numeric", label = "mtry"),
  grid = function(x, y, len = NULL, search = "grid") {
    expand.grid(mtry = c(2, 4, 6, 8))
  },
  fit = function(x, y, wts, param, lev, last, classProbs, ...) {
    train_rf_with_weights(x, y, param$mtry)
  },
  predict = function(modelFit, newdata, submodels = NULL) {
    predict(modelFit, newdata)
  },
  prob = function(modelFit, newdata, submodels = NULL) {
    predict(modelFit, newdata, type = "prob")
  },
  predictors = function(x, ...) {
    colnames(x$trainingData)[colnames(x$trainingData) != ".outcome"]
  },
  varImp = function(object, ...) {
    randomForest::importance(object, ...)
  },
  levels = function(x) x$classes
)

# Train the Random Forest model with expanded grid
rf_model <- train(
  Loan_Status ~ ., 
  data = X_train, 
  method = rf_custom, 
  trControl = rf_control
)

# Predict on the test set
rf_predictions <- predict(rf_model, X_test)
conf_matrix <- confusionMatrix(rf_predictions, X_test$Loan_Status)

print("Confusion Matrix:")
print(conf_matrix)

# Extract metrics from confusion matrix
recall <- conf_matrix$byClass['Recall']
precision <- conf_matrix$byClass['Precision']
f1 <- 2 * (precision * recall) / (precision + recall)

# Get probabilities for ROC curve
rf_probs <- predict(rf_model, X_test, type = "prob")[, 2]

# Calculate ROC curve
rf_roc <- roc(X_test$Loan_Status, rf_probs)

# Plot ROC curve
print(plot(rf_roc, main = "Random Forest ROC Curve"))

# Calculate and display accuracy, AUC, recall, precision, and F1 score
rf_metrics <- data.frame(
  Accuracy = max(rf_model$results$Accuracy), 
  AUC = auc(rf_roc),
  Recall = recall,
  Precision = precision,
  F1_Score = f1
)
print(rf_metrics)

```